/**
 * 工单注册表 —— 项目的控制面（唯一允许"翻状态"的地方）。
 *
 * 职责：
 * 1. 记录每个待填充模块：工单号 / 文件 / 归属（strong=强模型专属 / weak=弱模型可领）/ 状态（open|done）
 * 2. 驱动测试激活：tests/utils/guard.ts 依据 status 决定单测是否跳过。
 *    翻 open→done 即激活该工单的全部测试；未实现就翻状态，测试立刻红（防作弊 K3）。
 *
 * 规则（由 scripts/check-tickets.mjs 在 CI 强制）：
 * - 代码中每个 NotImplementedError 引用的工单号必须存在且为 open
 * - 每个 open 工单对应的文件必须存在
 * - status=done 的工单，其文件中不得再出现 NotImplementedError
 *
 * 翻状态流程：实现完成 → npm run verify 绿 → 人工审查 git diff → 翻状态 → 提交。
 */

export type TicketOwner = 'strong' | 'weak'
export type TicketStatus = 'open' | 'done'
export type TicketArea =
  | 'ipc'
  | 'db'
  | 'service'
  | 'network'
  | 'reader'
  | 'library-ui'
  | 'notes-ui'
  | 'tags-ui'
  | 'settings-ui'
  | 'ui-kit'
  | 'hooks'
  | 'infra'
  | 'lineage'
  | 'e2e'
  | 'workspaces'

export interface Ticket {
  id: string
  file: string
  area: TicketArea
  owner: TicketOwner
  status: TicketStatus
  summary: string
}

export const TICKETS: readonly Ticket[] = [
  // ── infra：强模型已完成（骨架期实现，受锁契约的一部分）──────────────
  { id: 'SR-INFRA-01', file: 'src/main/db/connection.ts', area: 'infra', owner: 'strong', status: 'done', summary: 'SQLite 连接单例与 pragma' },
  { id: 'SR-INFRA-02', file: 'src/main/db/fts.ts', area: 'infra', owner: 'strong', status: 'done', summary: 'FTS5 查询转义工具' },
  { id: 'SR-INFRA-03', file: 'src/main/db/migrate.ts', area: 'infra', owner: 'strong', status: 'done', summary: '追加式迁移执行器' },
  { id: 'SR-INFRA-04', file: 'src/main/services/import_/file-store.ts', area: 'infra', owner: 'strong', status: 'done', summary: '受管文件存储（sha256 去重+路径净化）' },
  { id: 'SR-INFRA-05', file: 'src/main/http/http-client.ts', area: 'infra', owner: 'strong', status: 'done', summary: '出网客户端（host 白名单+超时+退避）' },
  { id: 'SR-INFRA-06', file: 'src/main/security/csp.ts', area: 'infra', owner: 'strong', status: 'done', summary: 'CSP 策略注入' },
  { id: 'SR-INFRA-07', file: 'src/main/security/shell-guard.ts', area: 'infra', owner: 'strong', status: 'done', summary: 'openExternal 外链白名单守卫' },
  { id: 'SR-INFRA-08', file: 'src/main/protocol/app-file.protocol.ts', area: 'infra', owner: 'strong', status: 'done', summary: 'app-file:// 受管文件协议' },
  { id: 'SR-INFRA-09', file: 'src/main/windows/main-window.ts', area: 'infra', owner: 'strong', status: 'done', summary: '主窗口与安全 webPreferences' },
  { id: 'SR-INFRA-10', file: 'src/main/windows/window-state.ts', area: 'infra', owner: 'strong', status: 'done', summary: '窗口位置记忆' },
  { id: 'SR-INFRA-11', file: 'src/main/bootstrap.ts', area: 'infra', owner: 'strong', status: 'done', summary: '组装根（依赖注入点）' },
  { id: 'SR-INFRA-12', file: 'src/main/ipc/register.ts', area: 'infra', owner: 'strong', status: 'done', summary: 'IPC 统一注册（zod 校验→service→Result）' },
  { id: 'SR-INFRA-13', file: 'src/preload/index.ts', area: 'infra', owner: 'strong', status: 'done', summary: 'contextBridge 白名单 API' },
  { id: 'SR-INFRA-14', file: 'src/renderer/api/client.ts', area: 'infra', owner: 'strong', status: 'done', summary: 'renderer 侧 IPC 客户端' },
  { id: 'SR-INFRA-15', file: 'src/main/dialogs.ts', area: 'infra', owner: 'strong', status: 'done', summary: '系统对话框注入（可测试）' },
  { id: 'SR-INFRA-16', file: 'src/main/services/index.ts', area: 'infra', owner: 'strong', status: 'done', summary: '服务装配桶' },
  { id: 'SR-INFRA-17', file: 'src/main/ipc/index.ts', area: 'infra', owner: 'strong', status: 'done', summary: 'IPC 装配桶（对话框/事件胶水）' },

  // ── ipc 薄分发层（weak）────────────────────────────────────────
  { id: 'SR-IPC-01', file: 'src/main/ipc/library.ts', area: 'ipc', owner: 'weak', status: 'done', summary: '文献库域 handler（list/detail/update-meta/collections）' },
  { id: 'SR-IPC-02', file: 'src/main/ipc/reader.ts', area: 'ipc', owner: 'weak', status: 'done', summary: '阅读器域 handler（open/标注读写/进度）' },
  { id: 'SR-IPC-03', file: 'src/main/ipc/notes.ts', area: 'ipc', owner: 'weak', status: 'done', summary: '笔记域 handler' },
  { id: 'SR-IPC-04', file: 'src/main/ipc/tags.ts', area: 'ipc', owner: 'weak', status: 'done', summary: '标签域 handler' },
  { id: 'SR-IPC-05', file: 'src/main/ipc/import_.ts', area: 'ipc', owner: 'weak', status: 'done', summary: '导入域 handler（对话框令牌）' },
  { id: 'SR-IPC-06', file: 'src/main/ipc/enrich.ts', area: 'ipc', owner: 'weak', status: 'done', summary: '元数据增强 handler（手动触发）' },
  { id: 'SR-IPC-07', file: 'src/main/ipc/export_.ts', area: 'ipc', owner: 'weak', status: 'done', summary: '导出域 handler（BibTeX/CSV/报告）' },
  { id: 'SR-IPC-08', file: 'src/main/ipc/settings.ts', area: 'ipc', owner: 'weak', status: 'done', summary: '设置域 handler（含网络诊断）' },
  { id: 'SR-IPC-09', file: 'src/main/ipc/system.ts', area: 'ipc', owner: 'weak', status: 'done', summary: '系统域 handler（外链守卫打开）' },

  // ── repos 数据访问层（weak）─────────────────────────────────────
  { id: 'SR-DB-01', file: 'src/main/db/repos/papers.repo.ts', area: 'db', owner: 'weak', status: 'done', summary: 'papers 表仓储（含 FTS 联查）' },
  { id: 'SR-DB-02', file: 'src/main/db/repos/annotations.repo.ts', area: 'db', owner: 'weak', status: 'done', summary: 'annotations 表仓储' },
  { id: 'SR-DB-03', file: 'src/main/db/repos/notes.repo.ts', area: 'db', owner: 'weak', status: 'done', summary: 'notes 表仓储（含 FTS）' },
  { id: 'SR-DB-04', file: 'src/main/db/repos/tags.repo.ts', area: 'db', owner: 'weak', status: 'done', summary: 'tags/paper_tags 仓储' },
  { id: 'SR-DB-05', file: 'src/main/db/repos/collections.repo.ts', area: 'db', owner: 'weak', status: 'done', summary: 'collections/paper_collections 仓储' },

  // ── services 业务层（weak）──────────────────────────────────────
  { id: 'SR-SVC-01', file: 'src/main/services/library.service.ts', area: 'service', owner: 'weak', status: 'done', summary: '文献库用例：列表筛选/详情聚合/元数据编辑' },
  { id: 'SR-SVC-02', file: 'src/main/services/reader.service.ts', area: 'service', owner: 'weak', status: 'done', summary: '阅读用例：取文件引用/标注读写/进度' },
  { id: 'SR-SVC-03', file: 'src/main/services/import_/import.service.ts', area: 'service', owner: 'weak', status: 'done', summary: '导入编排：对话框→file-store→抽取→入库' },
  { id: 'SR-SVC-04', file: 'src/main/services/import_/pdf-meta.extract.ts', area: 'service', owner: 'weak', status: 'done', summary: 'PDF 内嵌元数据与 DOI 抽取（纯函数）' },
  { id: 'SR-SVC-05', file: 'src/main/services/enrich/enrich.service.ts', area: 'service', owner: 'weak', status: 'done', summary: '增强编排：DOI/标题→provider→回写' },
  { id: 'SR-SVC-06', file: 'src/main/services/export_/export.service.ts', area: 'service', owner: 'weak', status: 'done', summary: '导出编排：对话框→序列化→写文件' },
  { id: 'SR-SVC-07', file: 'src/main/services/export_/bibtex.serializer.ts', area: 'service', owner: 'weak', status: 'done', summary: 'BibTeX 转义与序列化（纯函数）' },
  { id: 'SR-SVC-08', file: 'src/main/services/export_/markdown.report.ts', area: 'service', owner: 'weak', status: 'done', summary: '高亮+笔记→Markdown 读书报告（纯函数）' },
  { id: 'SR-SVC-09', file: 'src/main/services/tags.service.ts', area: 'service', owner: 'weak', status: 'done', summary: '标签用例（薄透传）' },
  { id: 'SR-SVC-10', file: 'src/main/services/notes.service.ts', area: 'service', owner: 'weak', status: 'done', summary: '笔记用例（含 NOT_FOUND 判定）' },

  // ── 开放 API providers（weak）───────────────────────────────────
  { id: 'SR-NET-01', file: 'src/main/services/enrich/providers/crossref.ts', area: 'network', owner: 'weak', status: 'done', summary: 'CrossRef REST 封装' },
  { id: 'SR-NET-02', file: 'src/main/services/enrich/providers/openalex.ts', area: 'network', owner: 'weak', status: 'done', summary: 'OpenAlex REST 封装' },
  { id: 'SR-NET-03', file: 'src/main/services/enrich/providers/arxiv.ts', area: 'network', owner: 'weak', status: 'done', summary: 'arXiv API 封装' },

  // ── reader 强模型模块（strong-open，Phase 3 决策门后实现）──────────
  { id: 'SR-RDR-01', file: 'src/renderer/features/reader/annotation-anchor.ts', area: 'reader', owner: 'strong', status: 'done', summary: '文本偏移↔DOM 定位纯函数（WADM 思路）' },
  { id: 'SR-RDR-02', file: 'src/renderer/features/reader/PdfPageCanvas.tsx', area: 'reader', owner: 'strong', status: 'done', summary: 'pdf.js canvas 渲染封装（v4 API；原 PdfCanvas.tsx 经 SR2-F-01 拆分为 PdfDocProvider+PdfPageCanvas——注册文件随直系继承者迁移，旧文件已删）' },
  { id: 'SR-RDR-03', file: 'src/renderer/features/reader/TextLayer.tsx', area: 'reader', owner: 'strong', status: 'done', summary: '官方 TextLayer CSS 接线' },

  // ── renderer UI（weak）─────────────────────────────────────────
  { id: 'SR-RDR-04', file: 'src/renderer/features/reader/ReaderPage.tsx', area: 'reader', owner: 'weak', status: 'done', summary: '阅读器页面组装（多 tab）' },
  { id: 'SR-RDR-05', file: 'src/renderer/features/reader/SelectionLayer.tsx', area: 'reader', owner: 'weak', status: 'done', summary: '文本选择→定位器交互层' },
  { id: 'SR-RDR-06', file: 'src/renderer/features/reader/AnnotationLayer.tsx', area: 'reader', owner: 'weak', status: 'done', summary: '标注渲染与命中层' },
  { id: 'SR-RDR-07', file: 'src/renderer/features/reader/ReaderToolbar.tsx', area: 'reader', owner: 'weak', status: 'done', summary: '阅读器工具栏' },
  { id: 'SR-RDR-08', file: 'src/renderer/features/reader/OutlinePanel.tsx', area: 'reader', owner: 'weak', status: 'done', summary: '目录/缩略图侧栏' },
  { id: 'SR-RDR-09', file: 'src/renderer/features/reader/reader.store.ts', area: 'reader', owner: 'weak', status: 'done', summary: '阅读器状态（打开文档/页码/缩放）' },
  { id: 'SR-LIB-01', file: 'src/renderer/features/library/LibraryPage.tsx', area: 'library-ui', owner: 'weak', status: 'done', summary: '文献库页面组装' },
  { id: 'SR-LIB-02', file: 'src/renderer/features/library/PaperList.tsx', area: 'library-ui', owner: 'weak', status: 'done', summary: '文献虚拟列表' },
  { id: 'SR-LIB-03', file: 'src/renderer/features/library/PaperRow.tsx', area: 'library-ui', owner: 'weak', status: 'done', summary: '文献行组件' },
  { id: 'SR-LIB-04', file: 'src/renderer/features/library/PaperDetailPanel.tsx', area: 'library-ui', owner: 'weak', status: 'done', summary: '文献详情侧栏' },
  { id: 'SR-LIB-05', file: 'src/renderer/features/library/FilterBar.tsx', area: 'library-ui', owner: 'weak', status: 'done', summary: '搜索与筛选栏' },
  { id: 'SR-LIB-06', file: 'src/renderer/features/library/ImportDropZone.tsx', area: 'library-ui', owner: 'weak', status: 'done', summary: '导入入口（拖拽+按钮）' },
  { id: 'SR-LIB-07', file: 'src/renderer/features/library/library.store.ts', area: 'library-ui', owner: 'weak', status: 'done', summary: '文献库状态（列表/筛选/选中）' },
  { id: 'SR-NOTE-01', file: 'src/renderer/shared/save-status.ts', area: 'notes-ui', owner: 'weak', status: 'done', summary: '笔记保存状态推导（C-03 自库侧面板下沉 shared；面板本体随 C-06 下线——文件登记随契约迁移）' },
  { id: 'SR-NOTE-02', file: 'src/renderer/features/notes/notes.store.ts', area: 'notes-ui', owner: 'weak', status: 'done', summary: '笔记状态' },
  { id: 'SR-TAG-01', file: 'src/renderer/features/tags/TagEditor.tsx', area: 'tags-ui', owner: 'weak', status: 'done', summary: '标签编辑器' },
  { id: 'SR-TAG-02', file: 'src/renderer/features/tags/TagFilter.tsx', area: 'tags-ui', owner: 'weak', status: 'done', summary: '标签筛选器' },
  { id: 'SR-TAG-03', file: 'src/renderer/features/tags/tags.store.ts', area: 'tags-ui', owner: 'weak', status: 'done', summary: '标签状态' },
  { id: 'SR-SET-01', file: 'src/renderer/features/settings/SettingsPage.tsx', area: 'settings-ui', owner: 'weak', status: 'done', summary: '设置页（含网络行为披露）' },
  { id: 'SR-SET-02', file: 'src/renderer/features/settings/settings.store.ts', area: 'settings-ui', owner: 'weak', status: 'done', summary: '设置状态' },
  { id: 'SR-UI-01', file: 'src/renderer/shared/ui/Button.tsx', area: 'ui-kit', owner: 'weak', status: 'done', summary: '按钮组件' },
  { id: 'SR-UI-02', file: 'src/renderer/shared/ui/Dialog.tsx', area: 'ui-kit', owner: 'weak', status: 'done', summary: '对话框组件' },
  { id: 'SR-UI-03', file: 'src/renderer/shared/ui/Toast.tsx', area: 'ui-kit', owner: 'weak', status: 'done', summary: 'Toast 通知组件' },
  { id: 'SR-HK-01', file: 'src/renderer/shared/hooks/useAsync.ts', area: 'hooks', owner: 'weak', status: 'done', summary: '异步调用 hook' },
  { id: 'SR-HK-02', file: 'src/renderer/shared/hooks/useDebounce.ts', area: 'hooks', owner: 'weak', status: 'done', summary: '防抖 hook' },

  // ── Phase 6 打包分发（strong，2026-08-22 开单）───────────────────
  { id: 'SR-PKG-01', file: 'electron-builder.yml', area: 'infra', owner: 'strong', status: 'done', summary: 'electron-builder NSIS 打包配置与 dist 编排（绑定预置/electronDist 复用/镜像下载）' },
  { id: 'SR-PKG-02', file: 'scripts/installer-smoke.mjs', area: 'infra', owner: 'strong', status: 'done', summary: '安装包冒烟：静默装→沙箱启动→存活断言→静默卸载' },

  // ── Phase 7 v2（strong，2026-08-23 B3 裁决后开单，b3 指针见各工单文件头）──
  // 领取纪律：按依赖序逐单领取逐单提交（KEY-01→KEY-02→ANNO-01/UIK-01），
  // 每单独立 verify+审查+翻状态；禁同批多单（AGENTS「只改这一个文件」条款）
  { id: 'SR2-KEY-01', file: 'src/renderer/shared/keymap.ts', area: 'hooks', owner: 'strong', status: 'done', summary: 'keymap 键盘快捷键单例（注册/注销成对+editable 避让）' },
  { id: 'SR2-KEY-02', file: 'src/renderer/features/reader/ReaderShortcuts.ts', area: 'reader', owner: 'strong', status: 'done', summary: '阅读器快捷键+ctrl 滚轮缩放（挂 keymap，翻页键位映射表）' },
  { id: 'SR2-ANNO-01', file: 'src/renderer/features/reader/AnnotationMenu.tsx', area: 'reader', owner: 'strong', status: 'done', summary: '标注四选项菜单（复制引文/删除/添加笔记/取消）' },
  { id: 'SR2-UIK-01', file: 'src/renderer/shared/ui/SplitPane.tsx', area: 'ui-kit', owner: 'strong', status: 'done', summary: '可拖拽分隔条容器（宽度持久化 localStorage）' },
  // ── Phase 7-B 多标签+同步状态投影（strong，2026-08-24 链条核查后开单；依赖序
  //    TABS-01→02→03→04，UNDO-01 依赖 TABS-01（closeTab 清理接缝）可与 02/03/04
  //    并行；每单独立 verify+审查+翻状态，禁同批多单）──
  { id: 'SR2-TABS-01', file: 'src/renderer/features/reader/reader.store.ts', area: 'reader', owner: 'strong', status: 'done', summary: 'reader.store per-tab 多文献字典重构（tab 生命周期状态机+竞态守卫 per-tab 化）' },
  { id: 'SR2-TABS-02', file: 'src/renderer/features/reader/TabBar.tsx', area: 'reader', owner: 'strong', status: 'done', summary: '阅读器多标签栏（order/activeId 消费，loading/error 态，关闭叉）' },
  { id: 'SR2-TABS-03', file: 'src/renderer/features/reader/tab-dirty.ts', area: 'reader', owner: 'strong', status: 'done', summary: '灰点信号聚合（annotations 失败+notes pending 两写面 → tab dirty 投影）' },
  { id: 'SR2-TABS-04', file: 'src/main/windows/main-window.ts', area: 'infra', owner: 'strong', status: 'done', summary: '退出拦截（close preventDefault+dirty 上报通道+二次确认）' },
  { id: 'SR2-UNDO-01', file: 'src/renderer/features/reader/annotation-undo.ts', area: 'reader', owner: 'strong', status: 'done', summary: '标注操作级撤销栈（create/delete/comment-edit 逆操作，per-tab）' },

  // ── Phase 7-C 笔记结构化重构（strong，2026-08-26 开单；b3 指针=B3 裁决 1（α
  //    双层）/3（DB 真相源+md 投影）+ROADMAP P7-C N1 增补块（蓝图 §4.3）；验收细目
  //    =ADR-0011 v1.1；依赖=偏序（02/03 仅依赖 01；04 依赖 03；05/06 依赖 04），
  //    执行按号序串行领取逐单提交（禁同批多单——AGENTS「只改这一个文件」条款）──
  { id: 'SR2-C-01', file: 'src/shared/annotation-order.ts', area: 'infra', owner: 'strong', status: 'done', summary: '片段序单源纯函数（页→页内偏移→创建序→id 全序；排序禁字符串字典序）' },
  { id: 'SR2-C-02', file: 'src/main/services/export_/corpus.assemble.ts', area: 'service', owner: 'strong', status: 'done', summary: 'corpus md 装配纯函数（ADR-0011 v1.1 口径+R12 装配单源条款）+单篇/全库导出通道与入口' },
  { id: 'SR2-C-03', file: 'src/renderer/features/reader/ReaderNotesPanel.tsx', area: 'reader', owner: 'strong', status: 'done', summary: '阅读器笔记面板（总评层 notes.store 消费+片段层列表；save-status 下沉 shared；ADR-0008 五模块不动）' },
  { id: 'SR2-C-04', file: 'src/renderer/features/reader/OutlineAside.tsx', area: 'reader', owner: 'strong', status: 'done', summary: '侧栏三栏宿主（目录/缩略图/笔记 tablist 上移+OutlinePanel mode 化+ReaderPage props 削减）' },
  { id: 'SR2-C-05', file: 'src/renderer/features/reader/anchor-locate.ts', area: 'reader', owner: 'strong', status: 'done', summary: 'N1 锚点定位服务（INV-20 三层防线 exact/page/paper 单入口+F-aware 滚动接缝+标注单击反向同步）' },
  { id: 'SR2-C-06', file: 'src/renderer/features/library/PaperDetailPanel.tsx', area: 'library-ui', owner: 'strong', status: 'done', summary: '库侧笔记编辑面下线（NotesPanel 删除+「去阅读器写笔记」入口——方案切换=删除旧方案红线）' },

  // ── Phase 7-G AI 传感器链条应用面第一批（strong，2026-08-27 开单；b3 指针
  //    =B3 增量裁决 D1-D6+七问 v1+第四轮增容（蓝图 §4.3/ADR-0015）；母本
  //    =ai-module-plan v1.1 §4+ai-plan-review §5/§6（定稿增补+会话状态机表）；
  //    契约=ADR-0011 v1.1 五件套；INV-16/17/18 预登记随 02/03/04 锚定；依赖
  //    =偏序（02 依赖 01；03 依赖 02；04 依赖 03；05 依赖 03——目录契约），
  //    执行按号序串行领取逐单提交（禁同批多单）──
  { id: 'SR2-AI-01', file: 'src/main/db/repos/ai_notes.repo.ts', area: 'db', owner: 'strong', status: 'done', summary: 'ai_notes 数据基座（迁移 003+repo：一行一锚定段×一问 N2 粒度+role CHECK+自持锚定三元组与 annotations 解耦；v1 无生产者声明 R4）' },
  { id: 'SR2-AI-02', file: 'src/renderer/features/reader/CorpusExtractor.ts', area: 'reader', owner: 'strong', status: 'done', summary: '全文/图提取器（pdfjs 白名单三文件 INV-16+ESLint 机器锚+自持文档生命周期 R2+事件桥单向 R3+逐页背压）' },
  { id: 'SR2-AI-03', file: 'src/main/services/export_/corpus.export.service.ts', area: 'service', owner: 'strong', status: 'done', summary: '五件套导出会话（manifest 终局单写+清空重建+单飞 EXPORT_BUSY INV-18+幂等 sha INV-17+corpus.assemble 延展 R12+通道保留判定）' },
  { id: 'SR2-AI-04', file: 'src/renderer/features/settings/CorpusExportSection.tsx', area: 'settings-ui', owner: 'strong', status: 'done', summary: '设置页 AI 语料导出节（进度行+单飞 disabled+App 层订阅 useExportCorpusEvents INV-14+toast INV-02+e2e 全链含中断重跑）' },
  { id: 'SR2-AI-05', file: 'tools/ai-sensor/queue.mjs', area: 'infra', owner: 'strong', status: 'done', summary: 'zcode 工具骨架（SKILL.md+config.template+queue 断点续跑幂等——vitest 宿主 R11+config.json gitignore+tools 入 eslint 覆盖）' },

  // ── Phase 7-G AI 回灌与联动第二批（strong，2026-08-27 开单；b3 指针
  //    =第四轮增容裁决（蓝图 §4.3 E1~E7/N1~N4+ADR-0015）；契约=ADR-0015
  //    五节+queue/SKILL 既有工具面（AI-05 交付）；INV-19（随 09）/21（随 10）
  //    预登记随单锚定+INV-20 消费方级用例随 08 补（exact 层延展用例随 09）；依赖=偏序（06→07→08→09；
  //    10 依赖 06），执行按号序串行领取逐单提交（禁同批多单）；08→09 定序
  //    依据=09 硬依赖 08 两交付物（ai-note-style 分色单源+ai-notes.store
  //    数据单源——v5「08∥09」偏序经 plan 门细化）──
  { id: 'SR2-AI-06', file: 'src/main/services/ai_sensor/ai-sensor.service.ts', area: 'service', owner: 'strong', status: 'done', summary: '伴随进程文件协议（协议根 userData/ai-sensor 四成员：job 原子写幂等/status 心跳新鲜度判活单源/工具侧 companion 拾取+产物 corpus-ai 落盘；应用永不 spawn INV-21）' },
  { id: 'SR2-AI-07', file: 'src/main/services/ai_sensor/ai-notes-import.service.ts', area: 'service', owner: 'strong', status: 'done', summary: '回灌导入器（ai-notes/import+list 通道 [locked-change]；幂等=archive 账本 sha 去重+清面重灌；「v1 无生产者」声明解除；工具永不写 DB）' },
  { id: 'SR2-AI-08', file: 'src/renderer/features/reader/AiNotesSection.tsx', area: 'reader', owner: 'strong', status: 'done', summary: '笔记面板 AI 面（role×question 分节+ai-note-style 七问分色单源+只读+「AI 正在读」状态行六态机+「AI 读文献」按钮写 job+待导入按钮）' },
  { id: 'SR2-AI-09', file: 'src/renderer/features/reader/AiAnnotationLayer.tsx', area: 'reader', owner: 'strong', status: 'done', summary: 'AI 标注渲染对等（verifyQuote 重锚同几何管线/存储独立 INV-19/v1 只读/点击高亮跳面板/anchor-locate exact 层延展 data-ai-note-id）' },
  { id: 'SR2-AI-10', file: 'src/renderer/features/settings/ZcodeLinkSection.tsx', area: 'settings-ui', owner: 'strong', status: 'done', summary: '设置页 zcode 联动（检测五态三档 fs 纯检测+一键装技能 fs 复制+心跳=06 单源；不代启会话 INV-21 e2e 断言）' },

  // ── Phase 7-H 发展脉络图（strong，2026-08-27 开单；b3 指针=蓝图 §4.3
  //    第四轮裁决 E3/E4/E5+ADR-0014（lineage 数据模型与图形态边界）；
  //    契约=ADR-0014 §数据模型 DDL 字面+E3 形态（v1 时间树单父/v2 DAG
  //    升版条件）；INV-27（树单父 service 层不变量）随 01 登记；依赖
  //    =P7-G AI-06~10 已清（节点 core idea 数据面）+P7-C N1（INV-20 跳转）
  //    +AI-09 exact 层延展（data-ai-note-id）+P7-F 几何（F-aware 接口
  //    已冻结——anchor-locate 延展面就位，非阻塞）；偏序（02 依赖 01 通道+模型；
  //    03 依赖 02 画布/store；04 依赖 03 选择上抛面；05 依赖全组），执行
  //    按号序串行领取逐单提交（禁同批多单）──
  { id: 'SR2-LG-01', file: 'src/main/db/repos/lineage.repo.ts', area: 'db', owner: 'strong', status: 'done', summary: '脉络数据基座（迁移 004 ADR-0014 DDL+repo+lineage JSON 草稿导入全有或全无替换式+lineage 域立 [locked-change] 十一域穷举；树单父 INV-27 登记）' },
  { id: 'SR2-LG-02', file: 'src/renderer/features/lineage/lineage-layout.ts', area: 'lineage', owner: 'strong', status: 'done', summary: '布局纯函数（y 年份分层+x Reingold-Tilford 零依赖手写+手工覆盖优先）+只读 SVG 画布 pan/zoom INV-14+脉络第四视图 E4+lineage.store 数据单源' },
  { id: 'SR2-LG-03', file: 'src/renderer/features/lineage/LineageBoard.tsx', area: 'lineage', owner: 'strong', status: 'done', summary: '交互编辑（拖拽 x/y 覆盖 JSON Canvas+加删节点边改父+树约束 UI 守卫 INV-27）+自动保存 INV-04 同型+写四通道接线 [locked-change]+退出聚合扩面（不动 TABS-04）' },
  { id: 'SR2-LG-04', file: 'src/renderer/features/lineage/LineageSidePanel.tsx', area: 'lineage', owner: 'strong', status: 'done', summary: '节点侧板（元信息+core idea+AI 笔记分节分色复用 ai-note-style+人工笔记）+笔记双击跳阅读器（OPEN_PAPER_EVENT+INV-20 单入口消费方级用例）' },
  { id: 'SR2-LG-05', file: 'tests/e2e/lineage.spec.ts', area: 'e2e', owner: 'strong', status: 'done', summary: 'e2e 全链（导入→渲染真实文本→拖拽持久→树拒绝→侧板→双击跳转→保存失败退出拦截→主题节点；guard 占位翻 done 激活）' },
  { id: 'SR2-ENR-01', file: 'src/main/services/enrich/cited-by.service.ts', area: 'service', owner: 'strong', status: 'done', summary: '含金量抓取缓存（迁移 005 papers 三可空列+瀑布响应携带零新增请求+citedByPatch 强制刷新纯函数（0 与 NULL 判别 === null）+applyEnrichment 独立 citedBy 参数——PaperMetaPatch/update-meta 契约零触碰+paperDetailSchema 三 optional 字段）——D3-A 档 ADR-0011 契约字段供给；票面双门档 scripts/audits/enr-ticketing-*' },
  { id: 'SR2-ENR-02', file: 'src/shared/venue-tier.ts', area: 'service', owner: 'strong', status: 'done', summary: 'venueTier 映射与装配（b3: P7-G 裁决链在本头注声明——corpus.assemble.ts 头指针保持 P7-C 不动；三档种子表 venueToTier+front-matter/manifest 可选字段两形装配+citedByFetchedAt 配对省略+INTERFACE sha 消费者提示+ADR-0011 v1.2 补注）——依赖 ENR-01 数据面' },
  { id: 'SR2-F-01', file: 'src/renderer/features/reader/PageColumn.tsx', area: 'reader', owner: 'strong', status: 'done', summary: '页列几何与懒渲染回收（b3: P7-F；占位盒+视口±1 渲染+离屏>2 回收 IntersectionObserver+页列就绪管线+层实例化分工（SelectionLayer 单实例）+setPage 双源 scroll:to|none 防回弹+:125/:116 单页假设处遇+PdfCanvas 拆 PdfDocProvider/PdfPageCanvas 旧删+INV-16 白名单迁移 [locked-change]）；实现段预拆五段——票面 scripts/audits/p7f-ticketing-draft.md' },
  { id: 'SR2-F-02', file: 'src/renderer/features/reader/anchor-locate.ts', area: 'reader', owner: 'strong', status: 'done', summary: '四层多页化收口与跳页兼容（b3: P7-F 裁决链在本条声明——anchor-locate.ts 头指针保持 P7-C 不动，一文件双裁决链；verifyWhenReady :153 页限定+SelectionLayer 动态锚定根+跨页选区拒绝 toast+跳页全链 e2e；locateAnchor 签名零触碰=F-aware 冻结面）——依赖 F-01 页列' },
  { id: 'SR2-F-03', file: 'src/renderer/features/reader/scroll-progress.ts', area: 'reader', owner: 'strong', status: 'done', summary: '滚动进度回写恢复与键位迁移（b3: P7-F；六态状态机宪法前置——writing 用 scroll:none 防回弹/用户接管=wheel|keydown|pointerdown 三类非 scroll 信号/per-tab Record 记账+就绪时夹取恢复页顶+PAGE_KEYS 四键滚动步+空格新增；scroll-progress 模块拆分 store 净减；零迁移整数页粒度）——依赖 F-02 串行（ReaderPage 装配共享+受锁 e2e 排他）' },
  { id: 'SR2-F-04', file: 'tests/e2e/reader-scroll.spec.ts', area: 'e2e', owner: 'strong', status: 'done', summary: '缩放重定义与收官 e2e（b3: P7-F；注册文件=e2e 票 LG-05 先例；zoom 视口中心保持纯函数+fit-width 列宽基准+收官全链 spec——离屏回收/进度恢复/标注原位/键位/缩放锚/INV-01+ctrl+wheel 段迁移批 4+战役收官报告）——依赖 F-01/02/03 全部' },
  { id: 'SR2-F-05', file: 'src/renderer/features/reader/scroll-converge.ts', area: 'reader', owner: 'strong', status: 'done', summary: '程序滚动单容器收敛（b3: P7-F；验收缺陷 A 修复——TabBar 被 scrollIntoView 祖先传播顶出视口；真泄漏面=viewport scrollingElement 门一/门二双核准；scrollIntoNearestScroller 最近滚动祖先差值法（start/center）替换 PageColumn 段⑤+anchor-locate flashElement 两处原生 scrollIntoView+ReaderPage 根两分支 overflow-hidden+Toolbar shrink-0；INV-34 登记禁祖先传播；e2e 窄视口 TabBar 恒可见回归锁 scrollingElement+main 双零断言）[locked-change]——票面 scripts/audits/sr2-f-05-brief.md；依赖 F-01~04（段⑤/flash 链既有形态）' },
  { id: 'SR2-F-06', file: 'src/renderer/features/reader/PageColumn.tsx', area: 'reader', owner: 'strong', status: 'done', summary: '页间分隔与选区不透明（b3: P7-F；验收缺陷 B+C 视觉修复——B 页盒 var(--panel) 底+0 1px 4px rgba(0,0,0,.12) 阴影渲染/占位同底消色差跳动+gap 不动；C ::selection 半透明→不透明近似色（关键实证：Chromium 不解析 ::selection 的 color-mix 行 fallback 行才是生效行故两行都改 rgb(191 191 255)——门一探查快照+变异②双证据核准）+text-layer.css 头注偏离登记；e2e reader-text.spec 新 test 自守卫（B 页盒底色/阴影/与 --bg 可辨+C ::selection 无透明分量）；单测零触碰）[locked-change]——票面 scripts/audits/sr2-f-06-brief.md；依赖 F-01~05（PageColumn 排他）' },
  { id: 'SR2-F-07', file: 'src/renderer/features/reader/SelectionLayer.tsx', area: 'reader', owner: 'strong', status: 'done', summary: '划选自绘选区+AI 层去 multiply（b3: P7-F；复测缺陷 P1 修复——F-06 不透明 ::selection 遮 canvas 字形根因推翻：pdfjs 文本层 span color:transparent 字形在下层，半透明才透字，「压白底等效色」只对纯白底成立；B 案=::selection 置 transparent（两行同值死代码收敛单行）+SelectionLayer 按 anchor.rects 自绘 30% accent 半透明选区块（z:2/pointer-events:none/禁 multiply——单层单绘根除重叠 span 逐元素叠绘；247 行触 250 拆 SelectionRects/SelectionToolbar 两件 DOM 零变化）+AiAnnotationLayer 摘容器 multiply 保 opacity:0.45（与 AnnotationLayer 层间叠乘路径清零——AI-09 起既有机制）；门一 C 项层叠链源码级三判据全过+机制三断言锁回炉（e2e computed style mixBlendMode/pointerEvents/zIndex——F-06「审色值没审机制」教训同构残余堵口）；受锁 reader-text.spec F-06 小票 C 节守卫改写（transparent+自绘层+alpha∈(0,1)）+selection-layer.test 2 it）[locked-change]——票面 scripts/audits/sr2-f-07-brief.md；依赖 F-06（推翻其 C 案）+AI-09（层链既有）' },
  { id: 'SR2-ENR-03', file: 'src/renderer/features/library/PaperDetailPanel.tsx', area: 'library-ui', owner: 'strong', status: 'done', summary: '详情面板被引数透出（b3: ENR 域；验收缺陷 D 修复——UI 透出面缺位非 bug：数据链全通（迁移 005→detailById 装配→schema optional）唯独 renderer 零引用；「期刊」与「来源」间加一行 Row（citedByCount===undefined 空→Row 自动 —；零值显示 0）；新测试 paper-detail-cited.test.tsx 3 it always-active（124/缺省 —/零值 0 边界）；shared/models 零触碰）[locked-change]（新测试入锁 143→144）——票面 scripts/audits/sr2-enr-03-brief.md；依赖 ENR-01/02 数据面' },
  { id: 'SR2-LG-06', file: 'src/renderer/features/reader/open-paper-anchor.ts', area: 'reader', owner: 'strong', status: 'done', summary: '脉络跳转接笔记面板信号（b3: P7-H；验收缺陷 E2 修复——跳转链完整且定位成功但 OutlineAside tab 本地态不切；anchor 分支 locateAnchor 之前 req.aiNoteId 有值先发 notifyAiNoteHighlight（AI-09 全套语义复用：持久 state 切 notes tab+列表滚动高亮，tab 未开早发不丢失挂载后补切）；无锚/裸锚路径零触碰；受锁 lineage-side-panel.test 加 2 it（notify 先于 locateAnchor——invocationCallOrder 三破坏形态全红）+stub 池扩 notifyAiNoteStub）[locked-change]——票面 scripts/audits/sr2-lg-06-brief.md；依赖 LG-04 接缝（bus 载荷 aiNoteId）+AI-09 信号' },
  { id: 'SR2-LG-07', file: 'src/renderer/features/lineage/lineage-layout.ts', area: 'lineage', owner: 'strong', status: 'done', summary: '脉络布局非单调年份树修复+边 label 渲染（b3: P7-H；验收缺陷 E1 修复——兄弟约束仅共享年份层触发→年份-拓扑错位树（子比父早 119 年）offset 恒 0 全树退化单列；Frame 增根占位 rootLo/rootHi+兄弟约束增补 mergedRootHi+SIBLING_GAP−rootLo 下限（直接兄弟不论层必横向错开，深层不共享层仍可交错紧凑性保留）；M1 夹具四遍独立手推逐位吻合 {Brown=Reynolds=200,Cross=90,水锤史=310} 分叉可见；边 label 沿贝塞尔中点渲染（LineageEdges.tsx 拆件 61 行——Canvas 269 触 250 红线驱动；空串不渲染+data-edge-label 钩）+Board 摘预留声明；受锁 lineage-layout.test +3 it（M1 夹具/紧凑保持/跨夹具）+lineage-canvas.test 边 label it；auto-fit 观察项不做）[locked-change]——票面 scripts/audits/sr2-lg-07-brief.md；依赖 LG-02 布局件' },
  { id: 'SR2-LG-08', file: 'src/renderer/features/lineage/LineageSidePanel.tsx', area: 'lineage', owner: 'strong', status: 'done', summary: '脉络跳转挂载时序竞态修复（b3: P7-H；复测缺陷 P3 修复——取证三级跳：交接书数据面假说被只读 SQL 推翻（真库 Synapse Remake/synapse.db ai_notes 四 paper_id×22 均匀+nodes 四绑定各异；com.synapse.app 下为陈旧残留库），主控亲读七跳全对，根因=ReaderPage 挂载效应闩锁消费 :118-119 先于监听器注册 :121——locateAnchor→waitOpen 同步重发 requestOpenPaper 事件自丢失（唯一在场监听器=App setView no-op）→无角色调 store.openPaper→8s 超时停留原 tab=「总跳最后打开的文章」，滞留闩锁下次 remount 迟到打开=「篇内定位正常」自洽；tab 已开/页内路径无竞态=e2e 全绿原因；StrictMode 双挂载旧序意外自愈=dev/e2e 表现分裂佐证）；修法=addEventListener 提前 3 行换序（挂载期外无未注册窗口——联审独立推演+全部派发点攻击维持）+防御修 LineageSidePanel:134 n.paperId（条目自身归属）；新测试 reader-page-open-race.test 入锁（bus/store/anchor 链全真件，mock 面三件不在竞态链——首红 spy 0 次+变异复红同错同行号=真锁时序））[locked-change]——票面 scripts/audits/sr2-lg-08-brief.md；依赖 LG-04 总线载荷链+LG-06 面板信号' },
  { id: 'R1-WS1', file: 'src/main/services/workspaces/workspace.service.ts', area: 'workspaces', owner: 'strong', status: 'done', summary: '课题域主进程·库级隔离地基（ADR-0018 裁决：userData/workspaces/<id>/ 各含 synapse.db+files/，sha256 去重/FTS/备份天然按课题+受锁面最小+「切课题=切库」零跨库泄漏类缺陷面；三候选否决 collections 挂标与 topic_id 外键）——①装配容器化：data-layer.container.ts Proxy facade 稳定壳（ipc/index+register 零 diff 实证）热换 db/repos/services/fileStore；②workspace.service+fs：list/create/rename/switch（busy 串行守卫中文 DomainError+装配失败重试幂等）；③IPC workspaces 四通道受锁扩容（schemas+api-surface+contracts+preload）；④遗留迁移幂等（根 synapse.db+files 整体入 workspaces/default/——L0 态自裁：全新首启库留根不预建目录，门一独立取证裁为 e2e 种子配方（seed-paper 直插无建表+SEED_DB 写死根路径）唯一兼容解非设计缺陷；L0 会话内物化双段链回炉锚定）；⑤INV-35 登记（同时刻至多一课题库+switch 串行+指针损坏降级首课题）。门一 0B/3W/4N（W1/W2 状态机测试缺口回炉 3 it 全绿零实现变更）+门二 PASS（W4 死断言复活+N5 中文防线锚定二轮回炉）——双轮全闭环；新测试 workspace.test 14 it 入锁 145→146；e2e 24 passed=迁移兼容验收）[locked-change]——票面 scripts/audits/r1-ws1-brief.md；依赖 ADR-0018+bootstrap 装配先例' },
  { id: 'R1-WS2', file: 'src/renderer/features/workspaces/workspace.store.ts', area: 'workspaces', owner: 'strong', status: 'done', summary: '课题切换器渲染层（ADR-0018 渲染面：切课题=dirty 确认→IPC switch→location.reload 全新 stores 零 stale 态类别）——①workspace.store（load/create/rename/switch+内联 error 重试——门一 W1 回炉兑现头注契约）；②WorkspaceSwitcher 侧栏切换器（nav 品牌行下，文案/aria 零触碰）+设置面课题管理节（App slot 注入——quality 禁互引唯一合规路径自裁）；③will-navigate 同 URL 放行（shouldBlockNavigation 纯函数严格等值唯一放行——reload 机制必要+外站/异 file/data: 全 deny 护栏意图不变，门一独立安全裁决无绕过向量；deny 面三 it 双面锚定=W4 回炉）；④e2e workspaces.spec（种子→新建课题 B→reload 库空+脉络空态→切回完整=用户需求 R1 验收场景；加载终态锚防假绿窗=W2 回炉）；INV-35 ④渲染面随单登记（含无 FK 新表防悬置写警示）。门一 0B/4W/10N→回炉 W1/W2/W4→门二 PASS 全核销；新测试 4 件入锁 146→150；vitest 100 文件 779 用例+e2e 25 passed）[locked-change]——票面 scripts/audits/r1-ws2-brief.md；依赖 R1-WS1 四通道（组合回归锁闭 WS1-W3）' },
  { id: 'R3-TH1', file: 'src/renderer/shared/theme.css', area: 'ui-kit', owner: 'strong', status: 'done', summary: '视觉系统主题基建（用户需求 R3：UI 美术优化参考 aquaresearch+原神——设计定稿 docs/design/2026-08-28_visual-system.md，token 终值单一来源=mockup shell-library.html :root）——①theme.css v2：旧 9 键换值（暖纸白 --bg #f6f4ee/墨青 --accent #2c5f8a/暖灰边框——40 tsx 内联引用零churn 名兼容）+新增 27 键（--gold 金铜系/--ink 墨青侧栏/--font-display 衬线栈 Georgia/宋体/--shadow 1-2-3/--radius s-m-l/--panel-glass/--night 夜幕系 R2 预铺）+纸面丝纹底；②App 壳：墨青渐变侧栏+右缘金渐隐线+菱形品牌标+四内联 SVG 图标（零依赖红线）+金 active 左缘条+版本徽记 footer；WorkspaceSwitcher 夜色最小适配；③共享四件 skin（Button/Dialog/SplitPane/Toast）——联审捉 B1 真缺陷：Button 静态皮肤内联 style 恒压 :hover 类致 hover 提亮永不生效（CSS 级联）→回炉迁全类化+4 it 防线（含 hover 0.7/ghost gold 文本断言+形态锁）；④受锁必然红恰 1 处（F-06 bodyBg rgb(247,248,250)→rgb(246,244,238) 预裁③核准）+token 防漂移锁 theme.test；annotation 五色保持原值（e2e 精确断言锁定优先）。联审 B1/W1/N6→回炉→827 用例+e2e 25 passed；locks 150→152；对比度抽查 --accent 3.6→6.1:1 --ok 3.1→4.7:1 均改善）[locked-change]——票面 scripts/audits/r3-th1-brief.md；依赖设计定稿+mockup 摸鱼图（多模态两轮 8/10 定稿）' },
  { id: 'R2-LG9', file: 'src/renderer/features/lineage/LineageCanvas.tsx', area: 'lineage', owner: 'strong', status: 'done', summary: '脉络命之座星象板视觉重制（用户需求 R2「布局太丑」主战场——视觉规范=mockup lineage-constellation.html v2 多模态评审 7.5/10 交付线）：夜幕星空宿主（三层星点+星云四层 radial+✦ 装饰 pointer-events:none 不参与布局）+节点卡（defs linearGradient 三停 165° 渐变+L 金角饰 path+题名 #f5f3ea+衬线金年份）+金微光年份层带（12%α 线+菱形刻度+衬线标——初始视口偏左不可见=无 auto-fit 既有行为，归 R2-LG10）+边辉（feGaussianBlur 2.6 glow 金实链/虚线银推断）+图例两型+工具条玻璃化；拆件 LineageNodeCard/NightDecor（Canvas 245≤250）；消费 theme.css 夜幕 token 零复写；badge 文本不落画布（e2e T4 strict 单源自裁）。联审 0B/1W/6N PASS（视觉规范逐值对照无缺项+e2e lineage 4 条零必然红独立证实+defs 单份无 id 冲突+星空驻宿主不随 viewport——W1 首红/变异日志未落盘=证据缺口记录处置，联审独立推演自洽；N5/N6 层带标初始不可见与 pending-link 亮面板色归 LG10/后续）；5 新 it 入锁 152（渐变/角饰/夜幕宿主/图例/推断边）。verify 832 用例+e2e 25 passed）[locked-change]——票面 scripts/audits/r2-lg9-brief.md；依赖 R3-TH1 夜幕 token+LG-07 布局既有' },
  { id: 'R2-LG10', file: 'src/renderer/features/lineage/lineage-viewport.ts', area: 'lineage', owner: 'strong', status: 'done', summary: '脉络布局收官（LG-07 遗留池 auto-fit 观察项转正+LG9 N5 层带标可见性兑现）——①auto-fit：新拆件 lineage-viewport.ts（状态机 idle→fitting→fitted+userInteracted 两源置位 panbg pointerdown/滚轮 zoom+导入替换不抢视口+「适应视图」按钮唯一复位口）；包围盒含层带标签左缘（fit 后年份标可见=LG9 N5 验收兑现）+手工覆盖位参与+边距 80/120+k 钳制 [0.25,4]+jsdom 0 尺寸真实防御分支；transform 串格式逐字符保持；②题名三档宽 nodeWidth 180/220/260 纯函数单源三消费（既有 layout 夹具全短档零红实证）；③侧板三件夜化（mockup .side 逐值——testid/文案/QUESTION_COLOR 分色零改，lineage-side-panel.test 零红）；④受锁必然红恰 1 处（e2e lineage.spec T2 拖拽落点 k=1 假设→scale-aware 等强度化——取证 log 申报）；INV-36 登记（auto-fit 不抢视口语义）。联审 0B/3W/7N PASS（数学独立手算 k=440/344 tx=120+200k 逐值吻合=锁真数学非 stub 形态；T2 等强度无放宽；W1 BAND_LEFT 跨文件魔法数+W3 resize 不跟随归遗留池；W2 markUserInteracted 死代码回炉删除——宪法死代码即删）；8 新 it；首红/变异日志全落盘（LG9 W1 教训兑现）。verify 840 用例+e2e 25 passed（一次无关剪贴板 flake 重跑双绿））[locked-change]——票面 scripts/audits/r2-lg10-brief.md；依赖 R2-LG9 夜幕板+LG-07 布局' },
  { id: 'R3-LIB', file: 'src/renderer/features/library/library.css', area: 'library-ui', owner: 'strong', status: 'done', summary: '文献库视觉重制（用户需求 R3 库视图——视觉规范=mockup shell-library.html v2）：行→卡片网格（auto-fill minmax(340px,1fr)）+材质三件套（暖白渐变+inset 顶高光+background-clip 防亚像素缝）+hover 金 hairline+L 角饰显形+translateY/shadow 升档+衬线年份/两行截断题名 min-height/斜体 venue 空隐藏/6px 胶囊标签/tabular-nums；FilterBar chips 化（lib-chip-on 镜像 .chip.on）+DiamondRule 菱形分隔组件（.lib-rule* 三段迁 theme.css=R3-U4 复用单源）+ImportDropZone 金虚线透明底；PaperDetailPanel 衬线皮肤+空态 DiamondRule 居中（文案逐字）；新件 library.css/DiamondRule.tsx/library-cards.test；交互/文案/testid 全保留（e2e 25 零必然红）。门一 FAIL 3B/3W（真机截图多模态评审 6.5/10 三问题实因：拖放区色阶断裂/卡片层级扁平+空年份丑/详情空态死白）→回炉七项（透明底/字号阶差 14-600/11/10.5/空年份 9px 淡金◆/空态/选中卡金 hairline 独立裁/样式迁移）→门二 PASS（W1 选中卡 hover 级联塌缩——:hover (0,2,0) 压单类 (0,1,0)，主控亲修复合选择器 .lib-card.lib-card-selected 零红；真机复评条件留收官段）。16 it；首红/变异/rework1 日志全落盘。verify 856 用例+e2e 25 passed（F-04 偶发双复跑绿裁定零交集））[locked-change]——票面 scripts/audits/r3-lib-brief.md；依赖 R3-TH1 token+mockup v2' },
  { id: 'R3-RDRSET', file: 'src/renderer/features/settings/SettingsSection.tsx', area: 'settings-ui', owner: 'strong', status: 'done', summary: '阅读器周边+设置页视觉（视觉役收官单元——设计定稿浓度表：阅读器=装饰浓度最低）：ReaderToolbar 玻璃浮层（panel-glass+blur10+金底缘——border-b 等高 1px 换 CSS 零占位，F-05 shrink-0/flex-wrap/py-2 几何零变）+ghost 控件+衬线页码；TabBar active 金 hairline 底缘（inset 零占位）；OutlineAside 金缘 tab+ReaderNotesPanel h4 金左缘条节标（阅读器侧板保持亮面——夜色只属脉络域）；SettingsPage 分节卡+金节标衬线+节间 DiamondRule 复用（SettingsSection.tsx 拆件，作用域 CSS 自持节）；红线零触碰机检实证（AiAnnotationLayer/AnnotationLayer/SelectionRects/scroll-converge/PageColumn/multiply/z-index 九名 grep 计数全 0——F-07 层叠链+F-05 滚动收敛面不动）。联审 PASS 无返工（reader-text.spec 107 断言五次全量从未红；e2e 间歇红三线证据裁定环境波动+backdrop-filter 边缘贡献留 W1 观察项——再现 ≥2 立案 A/B 摘 blur）。3 新 it；首红/变异/rework 日志落盘。verify 859 用例+e2e 25 passed×2）[locked-change]——票面 scripts/audits/r3-rdr-set-brief.md；依赖 R3-TH1 token+R3-LIB DiamondRule' },
  { id: 'SR2-AI-11', file: 'src/renderer/features/reader/AiNoteGroupList.tsx', area: 'reader', owner: 'strong', status: 'done', summary: 'AI 笔记呈现轴转置（b3: P7-G；验收缺陷 F 修复——用户口径「问题一+一审:xxx。二审:xxx。裁决:xxx。」：groupNotes 按 AI_NOTE_QUESTIONS 单源序转置（{question,items}，空组剔除）+组头 QUESTION_LABEL 分色条+组内条目头 ROLE_LABEL 分段（QUESTION_LABEL 被顶替防冗余——门一核准贴口径，anchorPage/色点保留）；ROLE_LABEL 单源改值「一审/二审/裁决」（消费方两处=面板+脉络侧板——票面「三消费方」取证误差坐实，AiAnnotationLayer 仅消费 QUESTION_COLOR）；LineageSideAiNotes 同步转置不抽件（Rule of Three 维持）；shared 零触碰；受锁 3→5 扩容（门一核准必然红：lineage-side-panel.test+lineage.spec T4 接缝归责同步）；e2e ai-notes-section 2 test+lineage.spec T4 改写）[locked-change]——票面 scripts/audits/sr2-ai-11-brief.md；依赖 AI-08 分节件+AI-09 高亮' },
  { id: 'SR2-AI-12', file: 'src/renderer/features/reader/ai-note-style.ts', area: 'reader', owner: 'strong', status: 'done', summary: 'AI 笔记组头补原始命题（b3: P7-G；复测缺陷 P2 修复——组头仅「第N问」短标签读者对不上号，七问原始命题仓内零存在唯一源=蓝图 §4.2 表：QUESTION_TEXT 映射新增（七值机器抽取 diff 证逐字誊自蓝图；类型 Record<Exclude<AiNoteQuestion,divergence>,string>——divergence 为角色节非七问成员保持短标签，Exclude=编译器强制两消费位分歧唯一形态）+两消费位组头拼「第N问：原始命题」（AiNoteGroupList h4+LineageSideAiNotes h5——跨域单源自动同达合 INV-11）；纯 renderer 呈现面零 IPC 零 shared；受锁必然红 5 处先行留证（ai-notes-section×3+lineage-side-panel:291+e2e 两 spec）+ai-note-style.test TEXT 键集非空新 it；联审 0B/3W/5N PASS——誊录逐字性联审独立机器重演 diff 空，W3 Q4~Q7 文案持续锁定缺口记遗留池（键集断言拦键漂移不拦值漂移））[locked-change]——票面 scripts/audits/sr2-ai-12-brief.md；依赖 AI-11 转置组头位' },
  { id: 'SR2-F-08', file: 'src/renderer/features/reader/SelectionLayer.tsx', area: 'reader', owner: 'strong', status: 'done', summary: '划选视觉反馈回退官方原生半透明（F1 修正役 R1 路线——ADR-0019；复测站 3「全面失败+0.5~5s 延迟」根修）：①text-layer.css ::selection/::-moz-selection 回官方 rgba(0 0 255 / 0.25)（逐字对照 pdfjs-dist pdf_viewer.css:678-685；br 两规则保持 transparent）；②删 SelectionRects.tsx 整件+SelectionLayer 摘 overlay 计算/渲染（P10 方案切换=删旧）；③视觉通道=原生 ::selection（拖选第一帧即反馈，零 JS 链路——取证：自绘层 30% accent 合成 rgb(191,207,220) 近乎不可见+拖选期死寂=根因双实锤，O(n) 遍历 0~0.6ms 假说证伪）；④工具条/保存/undo/Escape 零变；AnnotationLayer 单层 multiply+AI 层去 multiply（F-07 层间修复）保留；⑤受锁两文件第三次改写：e2e F-06 小票 C 节（官方半透明精确值+selection-rects 防回归 0 计数+L7 延迟预算 toolbar≤1.5s）+unit F-07a 改防回归守卫/F-07b 删——票面 scripts/audits/sr2-f-08-brief.md；取证 scripts/audits/f1-forensics.report.md；三屋：实现 1.95M tok/858 用例绿+门一 PASS 0B/4W/7N+门二 PASS 零回炉（W3=INV-37 登记）；依赖 ADR-0019 裁决' },
  { id: 'SR2-F-09', file: 'src/renderer/features/reader/text-layer.css', area: 'reader', owner: 'strong', status: 'done', summary: '划选选中色改灰（用户令 2026-08-29：仿 WPS——灰色选中/标注纯色；v5 核查=标注纯色+重合不加重已成立零改）：text-layer.css ::selection/::-moz-selection rgba(0 0 255 / 0.25)→rgba(0 0 0 / 0.30)（≈白纸 #B3B3B3）；受锁 e2e reader-text.spec F-06 小票 C 节精确值断言+测试名同步；INV-37/ADR-0019 补记（用户指令偏离官方值的显式登记）；压缩路径票（单值变更+守卫同步，主控直做——变异红证 sr2-f-09-mutation.raw.txt：css 改回蓝→F-06 小票红点精确锁值；verify 858+locks+e2e 25 passed 全绿；v5b 真机像素证=差分区 93.3% 中性灰/均值 rgb(151,154,155)）；核查档 scripts/audits/f1-out/f1-forensics5.json+v5 截图+执行记录 sr2-f-09-record.md' },
  { id: 'R2-LG11', file: 'src/renderer/features/lineage/LineageNodeCard.tsx', area: 'lineage', owner: 'strong', status: 'done', summary: '脉络重制浅色严谨板（U2a=U2 修正役零 schema 先行单元——用户五决 2026-08-29 落地；R2-LG9 星象板方向否决后的修正延续=R2 系）：白卡+边框编码 A 线型×色阶（核心=accent 1.5 实线/普通=node-branch 1 实线/主题+综述=虚线 6-4；选中 +0.75）+foreignObject 题名换行 ≤3 行省略+title tooltip（LineageNodeCard:78 单行 text 根修）+nodeHeight 卡高单源（INV-38 三消费 1/2/3 行=64/82/100）+isSurvey/isCore 纯函数+综述布局右缘新列+综述关联边淡灰虚线 2-3（决3）+夜幕系脉络域摘除（.lineage-host 白底+LineageNightDecor 删+图例改写 LineageLegend 四项+工具条/适应视图/侧板三件白玻璃化+脉络衬线年份摘除=决5 连带）+BAND_LEFT 单源（B1 清账）；**isCore 出度口径修正（2026-08-29 真机复评裁决）**：初版「入度≥2」在 INV-27 树单父约束下数学恒假（合法图入度≤1 恒不触发；取证器 fixture 造双入边被 service 多父守卫拒=单测全绿≠真实数据形态可达的活证据）——「被引≥2 开宗立派」=≥2 继承者=出度≥2，主控压缩票直做（classify.ts+classify.test/visual.test 夹具同步+票面/INV-38 更正+变异红证 mutation-5.log 4 it 红）；受锁改写 lineage-canvas R2-LG9 块（拆 lineage-canvas-visual.test.tsx——max-lines 500）+lineage-layout 增两 describe+lineage-side-panel :311 夜化 it+新 lineage-classify.test（locks 163+取证器 r2-lg11-forensics.mjs 入锁=164）；e2e lineage.spec 零改（预裁兑现）；三屋：实现者 15.8M tok（875 用例精确命中 858−5+7+7+8）+门一 B0/W6/N9 PASS（6W 主控处置：W1/W2 申报、W3 主控补跑 mutation-4 GAP 精确值红、W4/W5/W6 遗留池）+门二 PASS 可直接收口；真机复评四线全过（wrapInBox/borderDiscernible/noRegression/surveyRight——取证档 scripts/audits/r2-lg11-out/ json+png；ABI 换绑 Windows 文件锁竞态=取证器 hash 校验防线+缓冲，环境怪癖常量化）；票面 scripts/audits/r2-lg11-brief.md+实现/门一/门二报告三份在档；裁决母本 docs/prompts/2026-08-29_loop-handoff-v3.md §2/§3' },
  { id: 'R2-LG12', file: 'src/main/services/lineage/lineage.service.ts', area: 'lineage', owner: 'strong', status: 'done', summary: '综述多参考边数据面（U2b——用户裁决 2026-08-29「A. 完整多参考边」AskUserQuestion 在案）：lineageEdge 增 kind:tree|ref（出口必填/upsert 可选缺省 tree/service+importDraft 双写路径显式填；draft 协议零改）+迁移 006（ADD COLUMN kind TEXT NOT NULL DEFAULT tree——旧行幂等+migrate.test [1..5,6]）+service upsertEdge 受控豁免分支（ref 豁免多父且 tree 侧收窄 ref 入边不算 tree 父=对偶自洽/仍拒环=混合图 reachable/同端点对 tree+ref 互斥拒/from 双条件 paperId≠null+isSurveyTitle——判定上移 shared/models 单源+renderer re-export 消费面零改）+layout 净化段剔 ref 边（不计 dropped——有意分流）+渲染 ref=var(--survey-edge) 1.4 虚 2-3（直读 e.kind，优先级 ref>综述关联>推断>普通）+综述右键「添加参考连接」入口（pending-link mode 扩展 ref）+INV-27 修订登记（tree 单父原样/ref 受控豁免条款）；受锁面=shared models+ipc schemas+006 迁移+lineage-import/layout/visual 三测+6 测试工厂 kind 波及+e2e lineage.spec T5（综述幽灵行第四篇独立 fixture→右键→点已有 tree 父的甲=豁免面→ref path 精确断言→reload 持久+负锚非综述无菜单项）；三屋：实现者 10.0M tok（883 用例精确命中 875+service6+layout1+visual1+变异红证 4 档含 M2 混合环盲区拦截/M4 自环 reason 红点）+门一 B0/W2/N6（W1=check-tickets R2 系正则盲区建单时已知设计、W2=主控 diff 包 git add 失误门一补全）+门二 PASS 零回炉（W3 剪贴板复验落盘补跑 2.0s 过/N7 首红未落盘教训回流）；收口：verify exit=0（locks 165=164+006）+e2e 26/26 终态（T5 首跑即过+corpus 超时 2.5s 单跑复验=负载 flake+剪贴板 2.0s 复验）；票面 r2-lg12-brief.md+三报告+收口单在档' },
  { id: 'R2-SH1', file: 'src/main/bootstrap.ts', area: 'infra', owner: 'strong', status: 'done', summary: '应用重命名 Synapse Remake→Synapse+userData 数据迁移（U3a——独立成票单独审计·handoff §8；⚠landmine=userData 目录名派生自 productName=用户真实数据目录搬迁，复用 WS1 幂等模式）：package.json name/productName 同步+文本消费位（main-window 标题/App 品牌位/index.html title 超票面发现+受锁 smoke.spec/app-shell.test 断言）+grep 口径修正（消费/注释面清零；迁移模块+测试功能面字面量 6 处=契约钉死豁免——门一 W1 结构性调和裁决）；迁移=独立模块 migrate-user-data.ts（纯 node:fs 零 electron 可测性）bootstrap 最早段——分支矩阵：旧在新无→renameSync 原子迁移+显式 setPath（Electron 启动期缓存派生值=实现者超票面发现，userDataDir 取值在迁移后=时序无竞态主控独立核实+门一交叉验证）；新已存在→跳过（天然备份）；皆无→全新；rename 失败→回落旧路径运行（数据安全优先）+warn；受锁=constants 邮箱域/smoke/app-shell 三件+新测试 5 it（分支矩阵全测+setPathCalls 显式断言）+locks 166；门一 B0/W3/N10（W-G1 electron-builder.yml 钉旧名=票面「无安装器面」前提失实→主控直改 productName/artifactName；W-G2 ci 强制 [dep-change]→收口双尾注；W-G3 lockfile root name→主控直改）+门二 PASS 零回炉（grep 亲测 6 命中分类正确+sha256 独立复算逐位命中）；W4 local-state.mjs 取证器路径随收口改（新目录优先+旧名兜底）；**真机迁移验证（备份-换装舞步）**：39M 真实库 tmp 全备份→首启=窗口标题 Synapse+双课题结构完整迁入新位+旧位 rename 走→二启幂等（跳过分支+旧位零重建）；verify exit=0（888 用例=883+5 精确命中）+e2e 全量 26；提交双尾注 [locked-change]+[dep-change]——票面/三报告/收口单在档' },
  { id: 'R2-SH2', file: 'src/renderer/app/App.tsx', area: 'infra', owner: 'strong', status: 'done', summary: '顶栏身份区+字体衬线消费清零（U3b——决4/决5 纯执行）：App 壳 header 条 h-11=44px（logo+Synapse 应用名+WorkspaceSwitcher 迁位零触碰+ver 随迁）+侧栏品牌行删+B1 wrapper+max-height 防展开错位+B2 header z-index 防盖板+--font-display 消费五类+lib 三类（W2 主控压缩票补——票面清单漏 library.css，决5「lib 衬线年份」明文）清零（token 定义保留）+--gold-night 别名退役（定义删+theme.test 同步）+三负锚（theme.css/library.css/font-display+gold-night 定义）；受锁=app-shell（品牌断言侧栏→顶栏+新 it 三件）/theme（负锚+TOKENS 删行）/r3-rdr-set-visual（:151 旧衬线锁→决5 负锚改写=同向双保险非放宽——实现者自裁）；三屋：实现者 2.9M tok（890=888+3−1 精确命中+双变异）+门一 PASS 无回炉（B1/B2 防御必要性核实/switcher 零锚定复核/N1 verify 时序硬条件/W4 对比度升格）+门二 PASS 零回炉+主控 W2 压缩票（library 三处+负锚扩+mutation-3 红点+sed 行号错位结构修复实录）；真机复评（r2-sh2-out/header.png）：顶栏 44px computed 实测三件在场+侧栏品牌行 0 计数+全 DOM Georgia 消费 0+**W4 解除**（trigger 实际色深色 rgb(35,38,45) on 白底——门一米白推演错位）+F-05/INV-34=定高+flex 链推演+e2e 全量阅读器链证据组合——票面/三报告/收口单在档' },
  { id: 'F-R2', file: 'src/renderer/features/reader/scroll-converge.ts', area: 'reader', owner: 'strong', status: 'done', summary: 'ui-scale≠1 程序滚动落点漂移修复（v18 U1 闭环——H1 根因=gBCR 视觉差值 1:1 加本地 scrollTop，探针三场景三档数值闭合 160-450px；方案 B 算术折算：effectiveZoom 单源+scroll-converge start/center 折算+scroll-progress getPageBoxes 同批修；真机复验 −512.6→−0.6 基线级/next 旁支同根归位；先红 6+变异 M1~M4+verify 126 文件 1081；门一 Kimi 链首战 B:0/W:1/N:6 可收口——换源事件 kimi-main→kimi-backup 实战；INV-34 量纲附注；B-3/H3 证伪备案 v19；票面+报告+门一全套 scripts/audits/f-r2-*）' },
  { id: 'P7A', file: 'tests/e2e/reader-text.spec.ts', area: 'e2e', owner: 'strong', status: 'done', summary: 'P7-A 剪贴板竞态 flake 专项（v18 U2 闭环——六场六现+第七现实锤；修=清场标记+条件重读 5×200ms+失败可归因末次读值，断言锚不放宽；受锁先红=外部占用注入复刻（p7a-red1）；主控压缩票直做（预算降级，担责披露）；连跑 3 次 P7-A 全绿；票面 scripts/audits/p7a-ticket.md）' },
  { id: 'F-R3', file: 'src/renderer/features/reader/CorpusExtractor.ts', area: 'reader', owner: 'strong', status: 'done', summary: 'AUDIT-C C-1 修票（二波场 2026-09-02）：轨二 c=P6 泄漏闭（settleLoadTask 纯函数——加载失败 destroy 恰一次+自身拒绝吞并+await settle 后重抛原错误；loadPdfDocument 接线保 task 句柄；头注状态机表证伪格改如实双路径）；轨一 e=上游查证（f-r3-upstream-check.md：v5.5.207 已修主逃逸点 onFailure 终接守卫/6.3.289 另有 destroy() 族硬化/master pdfManagerReady 悬尾仍在）→**终裁不升级**（任一档位不承诺零同族噪声+跨 major 回归面不换 devtools-only 收益；升级再评估触发条件=上游悬尾族全消）；轨二 b=destroy 序列化不采（无消噪声收益+切换串行延迟确定代价）；INV-49 登记（worker-per-task+销毁序+接受残余+代理计数监控锚）；门一 Kimi 3B/2W/0N PASS+门二 deepseek 2B/1W/2N PASS（W1 变异红证缺口主控补销=变异 A 同引用重抛/B 恰一次/C 顺序 settle+顺序测试 1 it；W2 upstream 档补包+降噪论证补强）；实现者 GLM5.3 统一档 1.94M tok+主控压缩票三变异；票面 f-r3-fix-brief.md+报告 f-r3-fix-impl.report.md+四门审档在档' },
  { id: 'P7E-01', file: 'src/main/db/repos/tags.repo.ts', area: 'db', owner: 'strong', status: 'done', summary: '标签生命周期（改名/合并/删除——P7-E 预留点清扫首票；b3: P7-E+B1 §3 预留 tags.service.ts:16+TagEditor.tsx:92；repo 四方法含跨表事务/service 校验序（NOT_FOUND/CONFLICT/自合并 INVALID_REQUEST）/三 IPC 通道 [locked-change]/renderer store 命令型动作+TagFilter 右键管理面（TagLifecycle+TagLifecycleMenu 拆件）；态空间 S1~S10+INV-53 登记；门一 Kimi 0B/3W/3N（W3 Esc/W1 恒真口径回炉+W2 S10 豁免补记）+门二 deepseek PASS 零回炉；单测 132 文件 1142（+29）/e2e 34（+1）；票面 scripts/audits/p7e-01-brief.md+三报告档在案）' },
  { id: 'P7E-02', file: 'src/main/ipc/import_.ts', area: 'ipc', owner: 'strong', status: 'done', summary: '拖拽导入（P7-E 预留点清扫二票；b3: P7-E+B1 §3 预留 ipc/import_.ts:18+ImportDropZone.tsx:7；Design=fromPaths 通道对 renderer 隐藏（PRELOAD_HIDDEN_METHODS const+类型双消费单源）+apiDrag.importDropped 桥（webUtils 解析+planDroppedImports 三滤：合成 File 解析空串/类型门（File.type 为空剔除——目录项恒空类型）/后缀 .pdf+数量门 100 双层）——路径串不出 preload 堆；INV-07 修订（路径来源扩列）+INV-54 登记；态空间 D1~D8；门一 Kimi 0B/2W/2N（W2 目录命名 *.pdf 击穿→类型门回炉+M5 变异/N1N2 注释回炉；W1=门一包漏 tests/ diff 主控门二补包核实=纯减集改向）+门二 deepseek PASS 零发现；单测 135 文件 1160（+18）/e2e 35 用例 34+1 探针 flake 单现复跑绿未立案；票面 scripts/audits/p7e-02-brief.md+报告+双门审档在案）' },
  { id: 'B7', file: 'src/main/services/tags.service.ts', area: 'service', owner: 'strong', status: 'done', summary: 'tags upsert 纯空格名空判守卫（AUDIT-B W1 修票——B7 探针实锤 upsert 空格串入库 name 空行；修=对齐 rename 先例 trim 空 INVALID_REQUEST；主控压缩票 SR2-F-09 形态；先红 2/绿 3/变异 M1 定点撤卫 2 红还原核毕；门一 Kimi PWW（W=程序序 registry 翻态在收口——历票惯例+N1 票面同步+N2 locks 收口兑现）+门二 deepseek PASS 零发现；verify 135 文件 1163/locks 251；票面 scripts/audits/b7-brief.md+双门审档在案）' },
  { id: 'C-A3', file: 'src/renderer/features/notes/notes.store.ts', area: 'reader', owner: 'strong', status: 'done', summary: 'AUDIT-C C-3 扫描 §1.2-a 主候选修票（二波场 2026-09-02）：notes 防抖悬置写三件套=①discard API（discardPendingEdit/discardAllPendingEdits——清 timer+四元数据+条目，幂等）②in-flight 代际守卫（discardGen 派发快照+.then/.catch 回调首行全 no-op——防回调复活条目）③接线两点（tab-dirty confirmCloseDirty 守门内弃改收口=一切 tab 关闭路径必经；workspace.store switchTo 确认后 discardAll——check-quality 白名单受控例外）；main 归属校验已在职零改动（notes.service findById→NOT_FOUND——扫描报告「FK 偶然兜底」口径修正）；跨格序列①②③④逐一测试锚（含 e2e 复活面端到端「已保存」载入锚）；INV-50 登记+INV-35④ 兑现修订；门一 Kimi 0B/3W/8N 条件 PASS（W1 reject 版序列②主控压缩票补销+变异恰红/W3 App 聚合含 notes pending 代码面核验成立/W2 load×discard 裁定接受残余=重建条目为服务器基线复活不可能）+门二 deepseek 终审；实现者 GLM5.3 统一档 6.18M tok+主控压缩票 W1 补锚；票面 auditc-a3-brief.md+报告 auditc-a3-impl.report.md+两门审档在档' },
  { id: 'P7E-03', file: 'src/renderer/features/reader/ReaderToolbar.tsx', area: 'reader', owner: 'strong', status: 'done', summary: '页内高亮搜索（P7-E 预留点清扫三票；b3: P7-E+B1 §3 预留 ReaderToolbar.tsx:7,163+ReaderShortcuts.ts:38；Design=索引全文档（逐页 getTextContent 文本域，未渲染页也计数）+高亮仅渲染窗口（TextLayer DOM span 建 Range 取 clientRects——pdfjs 4.10 每项恰一 span 前提，数量不符降级零高亮只计数）+代际守卫（submit 自增/close/reset 失效）+ReaderToolbar searchBox slot 兑现占位（缺席=旧占位兜底——受锁夹具零破坏）+ctrl+f 独立 keymap id reader-search（不经 ReaderShortcuts 受锁面）；新五源文件（reader-search.ts 纯函数域/store/ReaderSearchBox/SearchHighlightLayer/useReaderSearch）+Enter 提交制（再按=下一处/Shift+Enter 上一处/Esc 关）+两段式滚动（pageTurner→setPage scroll:to 页盒顶+active scrollIntoView 居中）；态空间 S1~S12 逐格锚+INV-55 登记；门一 Kimi FAIL 1B/3W/5N→回炉 R1 七修（S11 MO 重算锚+M6 代偿/bindDoc 会话身份记账修重挂漏洞/lastCentered store 记账防滚动劫持/wiring 三测/逐项安全降小写/S2 spy/descriptor 还原）→复核 PWW 新 2W→回炉 R2 三改（Enter trim 比较/IME isComposing 守卫——中文主路径/非保长语料注释诚实化）→定点复核 PASS 零发现+门二 deepseek PASS 零发现（首调 32k 截断 PARSE_ERROR→64k 重试通过）；实现者 GLM5.3 统一档三轮 ~32.0M tok（环境无 model 参数欠账披露）；单测 140 文件 1219（既有实测 136/1163——v31 基线 135 勘误+56 新增）/locks 256（251+5）/e2e 36（35+1）；环境事件=e2e 超时硬杀砸中 seedPaperRow 换绑窗（绑定残留已恢复+md5 亲验 electron-v146——隐患记档属受锁共享面）；票面 scripts/audits/p7e-03-brief.md+报告+三轮门审档在案）' },
  { id: 'P7E-04', file: 'src/main/ipc/export_.ts', area: 'ipc', owner: 'strong', status: 'done', summary: '导出剪贴板（P7-E 预留点清扫四票；b3: P7-E+B1 §3 预留 export.service.ts:27；Design=单通道 export/clipboard（format bibtex|csv 枚举+paperIds schema min(1) 空选集拒）+main 侧构建 main 侧写（内容不过 renderer——deps.clipboard 注入 electron.clipboard）+构建器单源（buildBibtex/buildCsv 直用零改）+先构建后写（失败零剪贴板副作用）+无对话框无 CANCELLED；PaperDetailPanel 248 贴 250 红线→usePaperDetailActions hook 拆件（215 行,受锁 paper-detail-export.test 零改全绿=拆件判据）+复制 BibTeX/复制 CSV 两按钮；态空间 E1~E8+INV-56 登记（构建器单源/剪贴板写单口/先构建后写/可选注入还原项）；门一 Kimi PWW(0B/1W/4N)→回炉 R1 三修（console.error 观测/ClipboardReq 死导出删/头注 C-06 票外叙述回退）→复核 PASS+门二 deepseek PASS 零发现；实现者 GLM5.3 统一档两轮 8.25M tok（环境无 model 参数欠账披露）；诚实申报在档=两受锁件 chmod 编辑（主控派发令误称预解锁——收口 reapply 收账）+IpcDeps.clipboard 可选化（受锁 makeIpcDeps 桩工厂禁改+响亮守卫——还原项登记）；单测 142 文件 1231（+2 文件+12 用例）/locks 259（256+3）/e2e 37（36+1——主进程 clipboard.readText 读回 P7-A 先例+清场竞态防线）；票面 scripts/audits/p7e-04-brief.md+报告+两门审档在案）' },
  { id: 'P7E-05', file: 'src/main/services/reader.service.ts', area: 'service', owner: 'strong', status: 'done', summary: '阅读时长统计（P7-E 预留点清扫五票；Design=搭车 saveProgress 单通道（secondsDelta int 0..3600 optional——旧载荷零兼容）+008 迁移（预留写 002 勘误实落 008）+reading-time.ts 独立模块（deps 注入 crib scroll-progress）+复合 flusher（进度页+时长账单 invoke）+repo 原子累加（reading_seconds=reading_seconds+?）+ready×visible 双计时门+chunkSeconds 3600 分片单源三消费点；态空间 R1~R10+跨格锚（R3×R6/4000 分片/dispose 双 invoke/可见零头结转）+INV-57 登记（含注记面四件：R7 双 invoke/分片级部分丢失/无 24h 钳制/sec<0 不可达）；三屋全程=首轮 BLOCKED（票面×受锁 golden 双死结：migrate.test [1..7] 断言+10 件 PaperDetail 字面量）→主控 [locked-change] 12 件配套（migrate.test [1..8]+lineage-tags 7→8+10 字面量补字段——零断言语义弱化）→TDD 全流程（首红 5/1235→绿→M1~M4）→R1 主控亲验回炉（settle force 不检查 isVisible=hidden 段虚计）→R2 门一 BLOCKING 回炉（3600 上界×收尾口回吐结构冲突——invokeOne 分片+M6）→R3 门二 BLOCKING+WARN 回炉（dispose 尾账未分片同型漏点→chunkSeconds 单源三消费点+M7；settle 吸收/结转绑死→解耦+锚语义随裁决变更）；M2 变异载体失效转移 M5 实录（防线冗余实证）；门一 Kimi（kimi-backup，主源 504 换源）FAIL（1B+3N）→R2→复审 PASS；门二 deepseek 64k 档 FAIL（1B+1W）→R3→复审 PASS_WITH_WARNINGS（落盘静默=既有尽力而为规约归注记）；主控亲验=TagEditor key 修复（e2e tag-lifecycle 确定性红两次复跑+回退 Panel 对照实证=既有竞态被本票加行踩宽——挂接点 key={detail.id} 会话身份语义，挂错文献正确性缺陷非仅测试面）+R3 超回炉上限 ≤2 超额披露（门一/门二各贡献独立轮非同案缠讼，人类复核可否决）；实现者 GLM5.3 统一档五轮 30.4M tok；verify 146 文件 1255（+4 文件+24 用例）/locks 265（259+6：4 unit+1 e2e spec+1 sql）/e2e 38 全绿（37+1——主控亲验三跑）；票面 scripts/audits/p7e-05-brief.md+报告 p7e-05-impl.report.md+两门审档在案）' },
  { id: 'P7E-06', file: 'src/renderer/features/tags/TagFilter.tsx', area: 'tags-ui', owner: 'strong', status: 'done', summary: '标签多选过滤（P7-E 预留点清扫六票；Design=AND 交集+切换删旧 tagId 加 tagIds（array min1 max20 optional 空数组 schema 拒收）+逐标签 EXISTS 循环参数绑定+chip toggle+INV-53 多选适配（消失 id 剔除非全清，顺序锚不变——INV-53 行内注记+预扫教训在档）；态空间 T1~T8 逐格锚+M1~M4 变异红证（M1 交集改 OR/M2 全清改反/M3 空数组不收敛/M4 toggle 只进不出）；受锁配套四件=[locked-change]（models/paper.ts 契约切换+repo:170 单选锚 tagIds:[t-1] 等价迁移+ui harness 多选形态 null→[] 等价载荷+tag-lifecycle.spec 插取消点击恢复换选序列——票面「e2e 零配套」预扫误判，实现者停手申报+快照铁证后主控裁决）；两项票外申报=tag-lifecycle 红（处置如上）+registry area 笔误（主控建单错误 renderer→tags-ui 修）；门一 Kimi（backup 源）PWW 零 BLOCKING（2W=waitForTimeout 先例同配方/预扫方法论缺口→INV-53 注记；3N 不阻塞——tagId 残留 grep 直证主控已补档）+门二 deepseek 64k PWW（2W=同 waitForTimeout/max(20) UI 无感知 UX 断层→后续票候选；1N btn! 风格）——零回炉双 PWW；实现者 GLM5.3 统一档两轮 6.76M tok；verify 148 文件 1265（+2 文件+10 用例）/locks 268（265+3）/e2e 39 全绿（38+1 新 spec——主控亲验）；票面+报告+两门审档在案）' },
  { id: 'P7E-07', file: 'src/main/services/library.service.ts', area: 'service', owner: 'strong', status: 'done', summary: '智能排序（P7-E 预留点清扫七票末项=**P7-E 余序清空**；Design=枚举加值 cited_desc（向后兼容旧三值全保留——与 P7E-06 切换删旧对照）+COALESCE(cited_by_count,0) DESC 空值显式归零垫底（探针前置实录：DESC 下 NULL 默认垫底但 0-vs-NULL 相对序由引擎决定——删 COALESCE 变异 M1 真实红）+rowid 决胜+双 Record<LibrarySort> 类型强制闭环（M2 漏键 typecheck 红证）+SORT_LABEL『被引（高到低）』+:20 预留注记兑现（含「经新 repo 方法」→「ORDER_BY 映射扩展」勘误）；态空间 S1~S5 逐格锚+M1~M3 变异红证还原空；门一 Kimi（backup）PWW 零 BLOCKING+门二 deepseek 64k PWW——双 PWW 零回炉（2 NIT 双门同题：schema 入参直锚 parse({sort:cited_desc}) 缺位→下次合法触碰该测试件时补+报告行数自报 106 vs diff 实证 111 申报精度——计数须机器实测纪律再证）；e2e 零新 spec（单测全锚+下拉 Object.entries 驱动——双门接受论证）——主控亲验全量 39/39（首轮 1 failed=reader-text:872 F-ARCH4-M1 与本票零交集+定向复跑绿+复验全绿=非确定抖动第 1 现记录指纹不立案）；实现者 GLM5.3 统一档一轮 1.69M tok；verify 149 文件 1270（+1 文件+5 用例）/locks 269（268+1）；票面+报告+两门审档在案）' },
  { id: 'F-A6', file: 'src/renderer/features/reader/selection-paint.tsx', area: 'reader', owner: 'strong', status: 'open', summary: '划选渲染错乱+拖选卡顿根治（用户实报 2026-09-03：某 PDF 选区灰块锯齿拼接/右侧溢出（图证在档）+选中延迟一卡一卡；五轮方案残留=F-A4 自绘并集层的 D1 rects evaluate 在异常 text-layer PDF 上错乱/D2 拖选期 200ms 防抖全量重算+portal 重渲染卡顿——历史 F-06/07/08/09/A4 五轮触发远超二次重构线，纪律=设计文档先行（态空间+两病根机理推演+方案对比）再实现；涉 ADR-0019 R3 修订；**a 取证票毕 2026-09-04**：f-a6-diag 三件（探针/库/页内采集器——五段探针+A/B 对照+tick 前测）+裁决表 f-a6-forensic-verdict.md（门一 Kimi PWW 回炉闭合+门二 deepseek PWW 4W2N 主控直裁落地，双档 §9-7/8）；核心裁定=**R-迁移为主修（阶段化决策门：阶段1 T1/T9 duckViewport 前置修复→阶段2 复跑 A/B 对照确认 S1/S2 消除→阶段3 主链迁移落地）**——真实库 46 页 T1/T9 零触发（合成 S1/S2 触发量化闭合：outside 5/8、平移 x+36.01/y−37.40）；真实样本甲乙同净（IoU 0.9996/0.9999）+mLR 对项盒结构性拆簇反证（211/151 vs 行真值 43/10）；用户实报重形态未复现（轻形态 3/39 行双块）——修复集以机理+合成证据裁定+验收条件随票流转（§5）；G2=偏离率≥5%（健康 0~0.12% vs 病理 25~62.5%，间隔≥200 倍）+右溢支占位+仅新增复现证据时启用；tick 基线=5Hz 步进实测（间隔 199.8~207.3ms）+每 tick gBCR≈101/gCS≈391（3882 页）；verify 149/1273/locks 272（269+脚本三件）全绿 [locked-change]；**b1 阶段 1+2 毕 2026-09-04**：T1/T9 前置修复（TextLayer duckViewport rotation/rawDims 真值化+rotatedContainerBox 容器旋转半边[pdf.mjs 4.10.38 源码级：span 恒未旋转用户空间百分比，页旋转由容器 CSS 变换承担——官方 pdf_viewer.css data-main-rotation 规则的内联等价]+PdfPageGeometry 第三参下钻[PdfPageCanvas→PageBox/PageColumn 纯类型扩→PagesOverlay→TextLayer geometry 必填无回退]）——**阶段 2 决策门过（门二终位 PASS+ENDORSE）**：s1rot outside 5/8→0/8+A_paint 1→3=行真值、s2crop 双向平移 36px→0.03/IoU 0.8213→0.9998、健康页块数逐位不变（1c2d IoU 0.9982=ENDORSE 度量精度改进）、tick 同量级；单测 text-layer.test 新 11 用例（duckViewport 直测+四旋转态+jsdom 语义级+transform-origin 锁）+变异红证 2；门一 Kimi PWW 2W3N 回炉闭合+门二 deepseek PASS 零 findings（档 f-a6b1-gate1/2）；裁决表 §10 决策门记录+两轮取证数据 f-a6-diag-out-a1/ 与 f-a6-diag-out/ 在档；verify 150/1285/locks 273 全绿亲验 [locked-change]——阶段 3 主链迁移待开工）' },
  { id: 'P7D-01', file: 'src/renderer/styles/', area: 'ui-kit', owner: 'strong', status: 'open', summary: 'P7-D 玻璃 UX 战役首票：design token 先铺（用户裁决 2026-09-03 开工且优先级高；**方向已裁 2026-09-03 在场轮=「乙字号+甲其余」**——批一闲时可动：动效 duration 7 档→--dur-* 变量+间距 inline 12 处（lineage 域六文件）清扫+层级弹层 {10,20,40,50} 语义命名，零视觉差（无头截图 diff 验收）；批二在场轮：字号 12 值→语义刻度 5~6 档+mockup 多模态评审+5 个 .5 半值归并逐档用户裁；底数盘点在档 docs/design/2026-09-03_p7d01-token-candidates.md——字号轴债最重 29 处/12 值、动效 32 token/7 档、间距 97% tailwind、层级近零债；B5 切换器面板 125% 档反差（×1.248）用户裁决认可=可接受设计，统一缩放体系复核产出核查结论供档不预改；视觉票面条款全套=批二适用）' },
  { id: 'P7X-01', file: 'src/renderer/features/tags/TagFilter.tsx', area: 'tags-ui', owner: 'strong', status: 'done', summary: '标签选中上限 UI 感知（P7E-06 门二 WARN 立项——用户裁决 2026-09-03 全立项；修=TagFilter toggle 添加方向守卫（!active && length>=TAG_FILTER_MAX→零变更+info toast「最多同时筛选 N 个标签」常量插值；移除方向永不设限）+TAG_FILTER_MAX=20 自 paper.ts 导出单源（schema .max 与 UI 同消费——漂移结构性消除故不登记 INV）；T8 拦截/T9 边界放行/T10 上界移除锚三 it+变异五证（M1 删守卫/M2 >=改>/M3 常量漂移→T8 红；M4 过严-1→恰 T9 红；M5 删 !active→恰 T10 红——deepseek 门二 WARN 回炉 R1 主控压缩补齐）；三屋全程=实现者（GLM 统一档欠账）+门一 Kimi K3（**ds-call 外链正式档**——PASS_WITH_WARNINGS 零 B 零 W 4N：T9 先红本性/aria 断言弱冗余/死 id 票外深化面/sha256 零仓库不可复算）+门二 deepseek v4flash（PWW 1W=T10 盲区已回炉销项/1N=TagFilter 不在锁面=锁范围本就不含 renderer 源码——收口说明核毕）+GLM 同源预审一轮（欠账披露——主控误降级门审链后被用户纠正，正式门审以 Kimi/deepseek 为准，预审不作放行依据）；verify exit=0 亲验（149 文件/1273 用例/locks 269）[locked-change]；票面 scripts/audits/p7x-01-brief.md+M1~M5 变异档+两门审 JSON 在案' },
  { id: 'P7X-02', file: 'src/renderer/features/reader/reading-time-setup.ts', area: 'reader', owner: 'strong', status: 'open', summary: '时长落盘重试/outbox（INV-57 注记候选立项——用户裁决 2026-09-03 全立项；分片级失败=部分静默丢失（尽力而为吞错规约）——重试或 outbox 兜底使尾账落盘失败可恢复；设计面=与 saveProgress 单通道的关系（禁双账本）+重启恢复语义）' },
  { id: 'P7X-03', file: 'docs/reports/', area: 'infra', owner: 'strong', status: 'done', summary: 'B6 模态期最小化语义对证（AUDIT-B 留场场——用户裁决 2026-09-03 全立项；**对证成立=结案推演升文档实证，免实现**（票面预判兑现）：机制链=tab-dirty.ts:110 window.confirm→Chromium 原生 owned-modal（探针 enabled:false 直接观测）→MSDN About Dialog Boxes 系统级明文「owner 禁用至对话框销毁+不可激活」+Electron 文档「modal disables parent」+native_window_views.cc SetEnabled→EnableWindow 源注（issue #50068 purposely disabled）+SO 3777551 任务栏同语义实证——门审质疑三点（归因推演/任务栏外推/应用层抑制未排除）逐点销项；边界申报=SC_MINIMIZE 精确内部路径无逐行源注但 B6 结论依赖的行为面三层闭合）；报告 docs/reports/2026-09-03_p7x03-b6-modal-minimize-crosscheck.md；B6 结案（AUDIT-B 留场场项销项）+Electron 模态边缘行为族附注监控备忘不入案' },
] as const

export const TICKET_MAP: ReadonlyMap<string, Ticket> = new Map(TICKETS.map((t) => [t.id, t]))

export function isTicketDone(id: string): boolean {
  return TICKET_MAP.get(id)?.status === 'done'
}

export function openTickets(): Ticket[] {
  return TICKETS.filter((t) => t.status === 'open')
}
